@echo off
cd /d "%~dp0"
echo Pulling today's news images generated by GitHub Actions...
git pull
if errorlevel 1 (
  echo git pull failed - check your internet connection or run this from a normal terminal to see the error.
  pause
  exit /b 1
)
echo.
echo Posting to Instagram + X...
call npm run post-only
echo.
pause
