import 'dotenv/config';
import { readFileSync } from 'fs';
import { basename, dirname } from 'path';
import { fileURLToPath } from 'url';
import { formatDate } from './renderCarousel.js';
import { buildInstagramCaption, buildTwitterText } from './caption.js';
import { postInstagramCarousel } from './postInstagram.js';
import { postTweet } from './postTwitter.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Posts images that were already generated by fetchNews.js + renderCarousel.js
// (used by the GitHub Actions workflow, after the images have been committed & pushed
// so they have a public URL Instagram's servers can fetch).
async function main() {
  const tz = process.env.TIMEZONE || 'Asia/Kolkata';
  const handle = process.env.HANDLE || '@__thedailybrief__';
  const { dateSub, iso } = formatDate(tz);
  const stories = JSON.parse(readFileSync(`${__dirname}/../data/latest.json`, 'utf-8'));

  const files = stories.map((_, i) => `${__dirname}/../public/${iso}/story${i + 1}.png`);
  files.unshift(`${__dirname}/../public/${iso}/cover.png`);

  const igCaption = buildInstagramCaption(stories, dateSub, handle);
  const publicBase = process.env.PUBLIC_IMAGE_BASE_URL;
  if (publicBase) {
    const imageUrls = files.map(f => `${publicBase.replace(/\/$/, '')}/${iso}/${basename(f)}`);
    try {
      await postInstagramCarousel(imageUrls, igCaption);
    } catch (err) {
      console.error('[postOnly] Instagram post failed:', err.message);
    }
  } else {
    console.log('[postOnly] PUBLIC_IMAGE_BASE_URL not set — skipping Instagram.');
  }

  const twitterText = buildTwitterText(stories, dateSub);
  try {
    await postTweet(files, twitterText);
  } catch (err) {
    console.error('[postOnly] Twitter post failed:', err.message);
  }
}

main().catch(err => {
  console.error('[postOnly] Fatal error:', err);
  process.exit(1);
});
